# Generated by Django 4.1.4 on 2024-04-18 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userModule", "0008_remove_complaint_user_usertbl_is_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="user_name",
        ),
        migrations.AddField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
