# Generated by Django 4.1.4 on 2024-04-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userModule", "0009_remove_complaint_user_name_complaint_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="user",
        ),
        migrations.AddField(
            model_name="complaint",
            name="user_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
