# Generated by Django 4.1.4 on 2024-04-19 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userModule", "0010_remove_complaint_user_complaint_user_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Complaint",
        ),
    ]
