# Generated by Django 4.1.4 on 2024-04-19 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userModule", "0011_delete_complaint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount_paid",
            new_name="amount",
        ),
    ]
