# Generated by Django 4.1.4 on 2024-04-19 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userModule", "0012_rename_amount_paid_payment_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="amount_paid",
        ),
    ]
