# Generated by Django 4.1.4 on 2024-04-19 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userModule", "0013_rename_amount_payment_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
