# Generated by Django 4.1.4 on 2024-04-19 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userModule", "0014_alter_payment_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="due_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
