# Generated by Django 4.1.4 on 2024-04-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userModule", "0015_payment_due_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstbl",
            name="delivery_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
